add_newline = true
# palette = "catppuccin_frappe"
format = """
$julia$python\
$hostname\
$jobs$character
"""
right_format = "$directory$git_branch$git_status$cmd_duration"

[python]
format = "$symbol"

[julia]
format = "[$symbol]($style)"
symbol = " "
style = "bg:none fg:yellow"

[character]
error_symbol = "[](red)"
success_symbol = "[](green bold)"
vicmd_symbol = "[](yellow)"

[jobs]
symbol = ""
format = "[]($style)[$symbol$number](bg:yellow fg:white)[ ]($style)"
style = "fg:yellow"

[cmd_duration]
disabled = false
format = "[]($style)[[󰔚 ](bg:black fg:white bold)$duration](bg:black fg:white)[ ]($style)"
style = "bg:none fg:black"

[directory]
format = "[]($style)[ ](bg:black fg:white)[$path](bg:black fg:white bold)[ ]($style)"
style = "bg:none fg:black"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
format = "[]($style)[[ ](bg:black fg:white bold)$branch](bg:black fg:white)[ ]($style)"
style = "bg:none fg:black"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:black fg:white)[ ]($style)"
style = "bg:none fg:black"
up_to_date = '✓'

[palettes.catppuccin_frappe]
base = "#303446"
blue = "#8caaee"
crust = "#232634"
flamingo = "#eebebe"
green = "#a6d189"
lavender = "#babbf1"
mantle = "#292c3c"
maroon = "#ea999c"
mauve = "#ca9ee6"
overlay0 = "#737994"
overlay1 = "#838ba7"
overlay2 = "#949cbb"
peach = "#ef9f76"
pink = "#f4b8e4"
red = "#e78284"
rosewater = "#f2d5cf"
sapphire = "#85c1dc"
sky = "#99d1db"
subtext0 = "#a5adce"
subtext1 = "#b5bfe2"
surface0 = "#414559"
surface1 = "#51576d"
surface2 = "#626880"
teal = "#81c8be"
text = "#c6d0f5"
yellow = "#e5c890"
