# config_directory/config.toml
[templates]

[templates.kitty]
input_path = "~/.config/matugen/colors-kitty.conf"
output_path = "~/.cache/matugen/colors-kitty.conf"

[templates.dunst]
input_path = "~/.config/matugen/dunstrc"
output_path = "~/.config/dunst/dunstrc"

[templates.vim]
input_path = "~/.config/matugen/colors-catppuccin-vim.lua"
output_path = "~/.config/nvim/lua/custom/plugins/colors-catppuccin.lua"

[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
prefix = '@'
swww_options = ["--transition-type", "any", "--transition-step", "255"]

[config.reload_apps_list]
waybar = true
kitty = true
gtk_theme = true
dunst = true

[config.custom_keywords]
font_mono = "Maple Mono NF"
font_sans = "Lexend"

[config.custom_colors]
# red = "#ff0000"
# yellow = "#ffff00"
# magenta = "#ff00ff"
# blue = "#0000ff"
# green = "#00ff00"
# cyan = "#00ffff"

bg = "#000000"

# ayu
red = "#f07171"
green = "#86b200"
yellow = "#F2AE49"
blue = "#41a6d9"
magenta = "#a37acc"
cyan = "#4cbe99"

# still ayu, but not only basic terminal colors
orange = "#f19618"
rosewater = "#f07078"
